# RTU配置
modbus_port=/dev/ttyS3
modbus_baudrate=4800
modbus_slave_id=1

# TCP配置
modbus_ip=192.168.2.1
modbus_tcp_port=5020

# CAN配置
can_interface=can0
can_bitrate=125000
can_enable=1
can_device_0=0x777
can_device_1=0
can_device_2=0
can_device_3=0
# MQTT配置
mqtt_broker=117.78.5.125
mqtt_port=1883
mqtt_client_id=69fe6602cbb0cf6bb958fad5_TempHumi_0_0_2026080901
mqtt_username=69fe6602cbb0cf6bb958fad5_TempHumi
mqtt_password=b178ada60b551cb59bc7c416d280ed6c37ba8207582d66bfc7fd0882827e009b
mqtt_topic=$oc/devices/69fe6602cbb0cf6bb958fad5_TempHumi/sys/properties/report
# ===== 华为云物模型配置 =====
mqtt_cmd_topic=$oc/devices/+/sys/command/#
service_id=Telemetry
prop_temp=temperature
prop_hum=humidity
prop_press=press



# ★★★ 继电器配置（新增） ★★★
relay_ip=192.168.0.10
relay_port=502
relay_slave_id=1

# ==================== TCP设备数组配置 ====================
# 设备0（与旧配置保持一致）
tcp_ip_0=192.168.2.1
tcp_port_0=50
tcp_slave_id_0=5
tcp_read_addr_0=0
tcp_read_count_0=3
tcp_enable_0=1


# 设备1（新增）
tcp_ip_1=192.168.2.1
tcp_port_1=50
tcp_slave_id_1=6
tcp_read_addr_1=0
tcp_read_count_1=2
tcp_enable_1=1



# 设备2（默认禁用）
tcp_ip_2=192.168.2.3
tcp_port_2=5020
tcp_slave_id_2=1
tcp_read_addr_2=0
tcp_read_count_2=2
tcp_enable_2=0

# ==================== RTU设备数组配置 ====================
rtu_port_0=/dev/ttyS3
rtu_baudrate_0=4800
rtu_slave_id_0=1
rtu_read_addr_0=0
rtu_read_count_0=2
rtu_enable_0=1

rtu_port_1=/dev/ttyS3
rtu_baudrate_1=4800
rtu_slave_id_1=2
rtu_read_addr_1=0
rtu_read_count_1=3
rtu_enable_1=1

rtu_port_2=/dev/ttyS3
rtu_baudrate_2=4800
rtu_slave_id_2=3
rtu_read_addr_2=0
rtu_read_count_2=4
rtu_enable_2=1

rtu_port_3=/dev/ttyS3
rtu_baudrate_3=4800
rtu_slave_id_3=4
rtu_read_addr_3=0
rtu_read_count_3=2
rtu_enable_3=0

